name: lynxprompt
base: core22
version: '0.1.0'
summary: CLI for LynxPrompt - Generate AI IDE configuration files
description: |
  LynxPrompt CLI helps you generate AI IDE configuration files
  (.cursorrules, AGENTS.md, copilot-instructions.md, etc.) directly
  from your terminal with an interactive wizard.

  Features:
  - Interactive wizard to create AI config files
  - Auto-detect project tech stack
  - Download blueprints from LynxPrompt marketplace
  - Browser-based OAuth authentication

  Usage:
    lynxprompt init     - Start interactive wizard
    lynxprompt login    - Authenticate with LynxPrompt
    lynxprompt list     - List your blueprints
    lynxprompt pull ID  - Download a blueprint

grade: stable
confinement: classic  # Needed for npm global install and browser opening

apps:
  lynxprompt:
    command: bin/lynxprompt

parts:
  lynxprompt:
    plugin: npm
    npm-node-version: "22.12.0"
    source: .
    npm-packages:
      - lynxprompt@0.1.0
    override-build: |
      craftctl default
      # Create wrapper script
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cat > $SNAPCRAFT_PART_INSTALL/bin/lynxprompt << 'EOF'
      #!/bin/bash
      exec "$SNAP/lib/node_modules/lynxprompt/dist/index.js" "$@"
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/lynxprompt


