apiVersion: v1
kind: Service
metadata:
  name: {{ include "lynxprompt.fullname" . }}
  labels:
    {{- include "lynxprompt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lynxprompt.selectorLabels" . | nindent 4 }}
